
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Atakan
 */




public class NewJFrame extends javax.swing.JFrame {
double  elemanSayisi;
double toplam;

double[] diziElemanlari = new double[999];
int sayac=0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        diziGiris = new javax.swing.JTextField();
        sonuc = new javax.swing.JTextField();
        ekle = new javax.swing.JButton();
        hesapla = new javax.swing.JButton();
        sifirla = new javax.swing.JButton();
        cikisYap = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        liste = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Uyarılar");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Dizi Elemanları Girişi:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Sonuç:");

        diziGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diziGirisActionPerformed(evt);
            }
        });
        diziGiris.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diziGirisKeyTyped(evt);
            }
        });

        sonuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonucActionPerformed(evt);
            }
        });

        ekle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ekle.setText("Ekle");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        hesapla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hesapla.setText("Hesapla");
        hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesaplaActionPerformed(evt);
            }
        });

        sifirla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sifirla.setText("Sıfırla");
        sifirla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifirlaActionPerformed(evt);
            }
        });

        cikisYap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cikisYap.setText("Çıkış Yap");
        cikisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisYapActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(liste);

        jLabel5.setText("Harf girmeyiniz!");

        jLabel4.setText("IBMF©");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aritmetik Ortalama", "Harmonik Ortalama", "Geometrik Ortalama", "Standart Sapma", "Medyan", "Mod" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Ondalık sayı girişleri nokta ile olacaktır (Örn: 2.3, 5.61...)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diziGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cikisYap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sifirla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hesapla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ekle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(diziGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(179, 179, 179))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ekle)
                        .addGap(48, 48, 48)
                        .addComponent(hesapla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sifirla)
                        .addGap(50, 50, 50)
                        .addComponent(cikisYap))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sifirlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifirlaActionPerformed
        // TODO add your handling code here:
        hesapla.setEnabled(false);
        sonuc.setEnabled(false);
        sifirla.setEnabled(false);
        sonuc.setText(null);
        diziGiris.setText(null);
        ekle.setEnabled(true);
        cikisYap.setEnabled(true);
        Number.clear();
        liste.setModel(Number);
        
        toplam=0;
        elemanSayisi=0;
        
        for( int i = 0; i < sayac; i++ ){
   diziElemanlari[i]=0;
        }
        sayac=0;
    }//GEN-LAST:event_sifirlaActionPerformed

    private void cikisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisYapActionPerformed
        // TODO add your handling code here:
        int c = JOptionPane.showConfirmDialog(null,"Emin misiniz?" ,"Sistemi Kapat" ,
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        
        if (c == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_cikisYapActionPerformed

    private void diziGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diziGirisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diziGirisActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        toplam =0.0;
        elemanSayisi=0.0;
        hesapla.setEnabled(false);
        sonuc.setEnabled(false);
        sifirla.setEnabled(false);

    }//GEN-LAST:event_formWindowActivated
DefaultListModel Number = new DefaultListModel();
    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
        // TODO add your handling code here:
        double num1 = Double.parseDouble(diziGiris.getText());
        
        diziElemanlari[sayac]=num1;
        sayac++;
        
        Number.addElement(num1);
        liste.setModel(Number);
        toplam = toplam+ num1;
        elemanSayisi= elemanSayisi +1;
        hesapla.setEnabled(true);
        diziGiris.setText(null);
        sonuc.setEnabled(true);
        sifirla.setEnabled(true);
         
        
        
    }//GEN-LAST:event_ekleActionPerformed

    private void hesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesaplaActionPerformed
        // TODO add your handling code here:

           double temp;
   for (int i = 1; i < sayac; i++) {
    for (int j = i; j > 0; j--) {
     if (diziElemanlari[j] < diziElemanlari [j - 1]) {
      temp = diziElemanlari[j];
      diziElemanlari[j] = diziElemanlari[j - 1];
      diziElemanlari[j - 1] = temp;
     }
    }
   }   
         
      
        String secilenIslem1 = jComboBox1.getSelectedItem().toString();
        
        if(secilenIslem1== "Aritmetik Ortalama"){
        String cevap;
        double ortalama=toplam/elemanSayisi;
        cevap = String.format("%.3f", ortalama);
        sonuc.setText(cevap);
        }
        
        else if(secilenIslem1== "Harmonik Ortalama"){
       
    double sum = 0.0;

    for (int i = 0; i < sayac; i++) { 
        sum += 1.0 / diziElemanlari[i]; 
    } 
    double cevap2= sayac / sum; 
    String cevapHarmonik;
        cevapHarmonik = String.format("%.3f", cevap2);
        sonuc.setText(cevapHarmonik);
        
            
        }
        
        
        else if (secilenIslem1=="Geometrik Ortalama"){
            
            
           
    double sum = diziElemanlari[0];

    for (int i = 1; i < sayac; i++) {
        sum *= diziElemanlari[i]; 
    }
     double cevap3=Math.pow(sum, 1.0 / sayac); 
     String cevapGeometrik;
     
           cevapGeometrik = String.format("%.3f", cevap3);
        sonuc.setText(cevapGeometrik); 
            
        }
        
        else if(secilenIslem1=="Medyan"){
            
            int middle = sayac/2;
    if (sayac%2 == 1) {
         
        double cevap4 =diziElemanlari[middle];
        String cevapMedyan;
        cevapMedyan= String.format("%.3f", cevap4);
        sonuc.setText(cevapMedyan);
    } else {
       double cevap5= ((diziElemanlari[middle-1] + diziElemanlari[middle]) / 2.0);
       String cevapMedyan;
                cevapMedyan= String.format("%.3f", cevap5);
        sonuc.setText(cevapMedyan);
    }
           /*    if (sayac % 2 != 0) {
                   double cevap10;
                   String cevapMedyan;
            cevap10 = diziElemanlari[sayac / 2]; 
            cevapMedyan= String.format("%.1f",cevap10);
            sonuc.setText(cevapMedyan);
               }
        double cevap11=(diziElemanlari[(sayac - 1) / 2] + diziElemanlari[sayac / 2]) / 2.0;
        String cevapMedyan;
        cevapMedyan=String.format("%.1f", cevap11);
        sonuc.setText(cevapMedyan);*/
        }
        
        else if(secilenIslem1=="Mod"){
            
            
            
                double maxValue, maxCount;
maxCount=0;
maxValue=0;
    for (int i = 0; i < sayac; ++i) {
        int count = 0;
        for (int j = 0; j < sayac; ++j) {
            if (diziElemanlari[j] == diziElemanlari[i]) ++count;
        }
        if (count > maxCount) {
            maxCount = count;
            maxValue = diziElemanlari[i];
        }
        
        }
        double cevap6 = maxValue;
        String cevapMod;
        cevapMod=String.format("%.3f",cevap6);
        sonuc.setText(cevapMod);
    
    
        }
        
        else if(secilenIslem1 == "Standart Sapma"){
            
            double StandartSapma = 0.0;
        int length = sayac;
 
       /* for(double sayi : diziElemanlari) {
            toplam1 += sayi;
        }*/
 
        double ortalama = toplam/length;
 
        for(int i=0; i<sayac;i++) {
            StandartSapma += Math.pow(diziElemanlari[i] - ortalama, 2);
        }
 
        
        
        double cevap12= Math.sqrt(StandartSapma/(length-1));
        String cevapStandartSapma;
        cevapStandartSapma= String.format("%.3f", cevap12);
        sonuc.setText(cevapStandartSapma);
            
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_hesaplaActionPerformed

    private void diziGirisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diziGirisKeyTyped
        char c= evt.getKeyChar();
        
        if((c== KeyEvent.VK_BACK_SPACE)
                ||(c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_diziGirisKeyTyped

    private void sonucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sonucActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cikisYap;
    private javax.swing.JTextField diziGiris;
    private javax.swing.JButton ekle;
    private javax.swing.JButton hesapla;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> liste;
    private javax.swing.JButton sifirla;
    private javax.swing.JTextField sonuc;
    // End of variables declaration//GEN-END:variables
}
